[package]
name = "rustls-tokio-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = { version = "0.23" }
rustls-pki-types = { version = "1.12" }
sha2 = { version = "0.10" }
tokio = { version = "1.47" }
tokio-postgres = { version = "0.7" }
tokio-rustls = { version = "0.26" }
x509-parser = { version = "0.17" }