[package]
name = "rustls-tokio-postgres"
version = "0.1.0"
edition = "2024"

[features]
default = []
channel-binding = ["dep:sha2", "dep:x509-parser"]
native-roots = ["dep:rustls-native-certs"]
webpki-roots = ["dep:webpki-roots"]

[dependencies]
rustls = { version = "0.23" }
rustls-native-certs = { version = "0.8", optional = true }
rustls-pki-types = { version = "1.12" }
sha2 = { version = "0.10", optional = true }
tokio = { version = "1.47" }
tokio-postgres = { version = "0.7" }
tokio-rustls = { version = "0.26" }
webpki-roots = { version = "1.0", optional = true }
x509-parser = { version = "0.17", optional = true }
